/**
 * components/MLInsightsPanel.tsx
 * ================================
 * Sidebar button that opens a modal showing live ML evaluation data
 * fetched from GET /api/v1/eval-report (served from eval_report.json
 * generated by ml/04_evaluate.py after training).
 */

import { useState, useEffect } from "react"
import { createPortal } from "react-dom"
import axios from "axios"
import type { Metrics } from "../types/api"

const BASE = import.meta.env.VITE_ML_URL ?? "http://localhost:8000"

const C = {
  blue600: "#0066CC", blue50: "#F0F7FF", blue100: "#E8F1FB",
  green600: "#00875A", green100: "#E3F5EC",
  amber600: "#B45309", amber100: "#FEF3C7",
  red600: "#C41E3A",
  purple: "#7C3AED", purple100: "#EDE9FE",
  ink900: "#0F1923", ink700: "#1E293B", ink500: "#475569",
  ink300: "#94A3B8", ink100: "#E2E8F0", ink50: "#F8FAFC",
  white: "#FFFFFF", surface: "#F4F7FB", border: "#DDE3EC",
}

const CATEGORY_COLORS: Record<string, string> = {
  utilities: "#7C3AED", groceries: "#00875A", transport: "#0891B2",
  shopping: "#B45309", entertainment: "#DB2777", other: "#94A3B8",
  subscription: "#6366F1", dining: "#0066CC", healthcare: "#059669",
}

interface EvalReport {
  accuracy:       number
  macro_f1:       number
  weighted_f1:    number
  train_accuracy: number
  n_estimators:   number
  categories:     string[]
  per_category:   Record<string, {
    precision: number
    recall:    number
    f1:        number
    support:   number
  }>
  feature_shape:  number[]
}

type Tab = "overview" | "eval" | "why" | "limits"

interface Props {
  metrics?: Metrics | null
  isOpen: boolean
  onClose: () => void
}

export default function MLInsightsPanel({ metrics, isOpen, onClose }: Props) {
  const [tab,    setTab   ] = useState<Tab>("overview")
  const [report, setReport] = useState<EvalReport | null>(null)
  const [loading,setLoading] = useState(false)
  const [error,  setError ] = useState<string | null>(null)

  // Fetch eval report when modal opens
  useEffect(() => {
    if (!isOpen || report) return
    setLoading(true)
    setError(null)
    axios.get<EvalReport>(`${BASE}/api/v1/eval-report`)
      .then(r => setReport(r.data))
      .catch(() => setError("Could not load eval report. Run ml/04_evaluate.py first."))
      .finally(() => setLoading(false))
  }, [isOpen])

  const tabs: { id: Tab; icon: string; label: string }[] = [
    { id: "overview", icon: "ti-brain",         label: "Overview"       },
    { id: "eval",     icon: "ti-chart-bar",      label: "Evaluation"     },
    { id: "why",      icon: "ti-bulb",           label: "Why RF"         },
    { id: "limits",   icon: "ti-alert-triangle", label: "Limitations"    },
  ]

  const Divider = () => (
    <div style={{ height: 1, background: C.border, margin: "14px 0" }} />
  )

  const InfoRow = ({ label, value }: { label: string; value: string }) => (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center",
      padding: "6px 0", borderBottom: `0.5px solid ${C.border}`, fontSize: 13 }}>
      <span style={{ color: C.ink500 , paddingRight : 12}}>{label}</span>
      <span style={{ color: C.ink900, fontWeight: 100 , justifyContent: "align-left" }}>{value}</span>
    </div>
  )

  const MetricCard = ({ label, value, sub }: { label: string; value: string; sub?: string }) => (
    <div style={{ background: C.surface, borderRadius: 8, padding: "10px 12px" }}>
      <div style={{ fontSize: 11, color: C.ink300, textTransform: "uppercase",
        letterSpacing: .5, marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: 20, fontWeight: 600, color: C.ink900, lineHeight: 1 }}>{value}</div>
      {sub && <div style={{ fontSize: 11, color: C.ink500, marginTop: 3 }}>{sub}</div>}
    </div>
  )

  const Badge = ({ text, type }: { text: string; type: "ok"|"warn"|"info" }) => {
    const s = { ok:{bg:C.green100,color:C.green600}, warn:{bg:C.amber100,color:C.amber600}, info:{bg:C.blue100,color:C.blue600} }[type]
    return <span style={{ background:s.bg, color:s.color, fontSize:11, fontWeight:600, padding:"2px 8px", borderRadius:99 }}>{text}</span>
  }

  // Build sorted category F1 list from live report
  const catF1 = report
    ? Object.entries(report.per_category)
        .map(([cat, m]) => ({ cat, ...m }))
        .sort((a, b) => b.f1 - a.f1)
    : []

  return (
    <>
      {/* Portal renders outside sidebar DOM — avoids stacking context issues */}
      {isOpen && createPortal(
        <div onClick={onClose} style={{ position:"fixed", inset:0,
          background:"rgba(15,25,35,.45)", zIndex:200, display:"flex",
          alignItems:"center", justifyContent:"center" }}>
          <div onClick={e => e.stopPropagation()} style={{ background:C.white,
            borderRadius:16, width:640, maxHeight:"85vh", display:"flex",
            flexDirection:"column", border:`1px solid ${C.border}`,
            boxShadow:"0 20px 60px rgba(0,0,0,.15)", overflow:"hidden" }}>

            {/* Header */}
            <div style={{ padding:"18px 24px", borderBottom:`1px solid ${C.border}`,
              display:"flex", justifyContent:"space-between", alignItems:"center",
              flexShrink:0 }}>
              <div style={{ display:"flex", alignItems:"center", gap:10 }}>
                <div style={{ width:32, height:32, borderRadius:8, background:C.purple100,
                  display:"flex", alignItems:"center", justifyContent:"center" }}>
                  <i className="ti ti-brain" style={{ fontSize:17, color:C.purple }} aria-hidden="true" />
                </div>
                <div>
                  <div style={{ fontSize:15, fontWeight:600, color:C.ink900 }}>ML Model Insights</div>
                  <div style={{ fontSize:12, color:C.ink300 }}>
                    RandomForest · {metrics?.classification_method === "ml_model"
                      ? "trained model active" : "keyword rules fallback"}
                  </div>
                </div>
              </div>
              <button onClick={onClose} style={{ background:"none",
                border:"none", cursor:"pointer", color:C.ink300, padding:4 }}>
                <i className="ti ti-x" style={{ fontSize:18 }} aria-hidden="true" />
              </button>
            </div>

            {/* Tabs */}
            <div style={{ display:"flex", borderBottom:`1px solid ${C.border}`, flexShrink:0 }}>
              {tabs.map(t => (
                <button key={t.id} onClick={() => setTab(t.id)} style={{ flex:1,
                  padding:"10px 8px", background:"none", border:"none", cursor:"pointer",
                  fontSize:12, fontWeight: tab===t.id ? 600 : 400,
                  color: tab===t.id ? C.blue600 : C.ink500,
                  borderBottom: tab===t.id ? `2px solid ${C.blue600}` : "2px solid transparent",
                  display:"flex", alignItems:"center", justifyContent:"center", gap:5 }}>
                  <i className={`ti ${t.icon}`} style={{ fontSize:14 }} aria-hidden="true" />
                  {t.label}
                </button>
              ))}
            </div>

            {/* Content */}
            <div style={{ flex:1, overflowY:"auto", padding:"20px 24px" }}>
              {loading && (
                <div style={{ textAlign:"center", color:C.ink300, padding:"40px 0", fontSize:13 }}>
                  <i className="ti ti-loader-2" style={{ fontSize:24, display:"block",
                    marginBottom:8 }} aria-hidden="true" />
                  Loading eval report…
                </div>
              )}
              {error && (
                <div style={{ background:C.amber100, borderRadius:8, padding:"12px 14px",
                  fontSize:13, color:C.amber600 }}>{error}</div>
              )}

              {!loading && !error && tab === "overview" && (
                <div>
                  <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:8, marginBottom:16 }}>
                    <MetricCard label="Algorithm"      value="Random Forest"
                      sub={report ? `${report.n_estimators} trees` : "200 trees"} />
                    <MetricCard label="Test accuracy"
                      value={report ? `${(report.accuracy*100).toFixed(1)}%` : (metrics?.ml_accuracy ? `${(metrics.ml_accuracy*100).toFixed(0)}%` : "—")}
                      sub="held-out test set" />
                    <MetricCard label="Train accuracy"
                      value={report ? `${(report.train_accuracy*100).toFixed(1)}%` : "—"}
                      sub="on training set" />
                    <MetricCard label="Train/test gap"
                      value={report ? `${((report.train_accuracy - report.accuracy)*100).toFixed(1)}%` : "—"}
                      sub="lower = less overfitting" />
                  </div>
                  <Divider />
                  <div style={{ fontSize:13, fontWeight:600, color:C.ink500,
                    textTransform:"uppercase", letterSpacing:.7, marginBottom:10 }}>Pipeline</div>
                  <InfoRow label="Raw data"        value="US govt cards · 700K rows" />
                  <InfoRow label="Features"
                    value={report ? `TF-IDF + numerical (${report.feature_shape[1] ?? 506} total)` : "TF-IDF (500) + 6 numerical"} />
                  <InfoRow label="categories"
                    value={report ? `${report.categories.length} (${report.categories.join(", ")})` : "8"} />
                  <InfoRow label="Class weighting" value="Balanced - handles imbalance" />
                  <InfoRow label="Inference speed" value="~2ms per transaction" />
                </div>
              )}

              {!loading && !error && tab === "eval" && (
                <div>
                  <div style={{ fontSize:13, fontWeight:600, color:C.ink500,
                    textTransform:"uppercase", letterSpacing:.7, marginBottom:4 }}>
                    Per-category F1 scores
                  </div>
                  <div style={{ fontSize:11, color:C.ink300, marginBottom:14 }}>
                    Live data from eval_report.json · F1 = harmonic mean of precision and recall
                  </div>
                  {catF1.length === 0 && (
                    <p style={{ fontSize:13, color:C.ink300 }}>
                      No data — run ml/04_evaluate.py to generate.
                    </p>
                  )}
                  {catF1.map(({ cat, f1, precision, recall, support }) => {
                    const color = CATEGORY_COLORS[cat] ?? C.ink300
                    const label = f1>=0.75 ? C.green600 : f1>=0.60 ? C.amber600 : C.red600
                    return (
                      <div key={cat} style={{ marginBottom:12 }}>
                        <div style={{ display:"flex", alignItems:"center", gap:10, marginBottom:3 }}>
                          <span style={{ fontSize:12, color:C.ink500, width:90,
                            textTransform:"capitalize", flexShrink:0 }}>{cat}</span>
                          <div style={{ flex:1, height:6, borderRadius:99,
                            background:C.ink100, overflow:"hidden" }}>
                            <div style={{ height:"100%", borderRadius:99,
                              width:`${f1*100}%`, background:color }} />
                          </div>
                          <span style={{ fontSize:12, fontWeight:600, color:label,
                            width:36, textAlign:"right" }}>{f1.toFixed(2)}</span>
                        </div>
                        <div style={{ paddingLeft:100, fontSize:11, color:C.ink300 }}>
                          P: {precision.toFixed(2)} · R: {recall.toFixed(2)} · n={support}
                        </div>
                      </div>
                    )
                  })}
                  <Divider />
                  <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:8 }}>
                    <MetricCard label="Weighted F1"
                      value={report ? report.weighted_f1.toFixed(3) : "—"} />
                    <MetricCard label="Macro F1"
                      value={report ? report.macro_f1.toFixed(3) : "—"} />
                  </div>
                </div>
              )}

              {!loading && tab === "why" && (
                <div>
                  {[
                    { title:"Handles mixed features",    body:"Combines TF-IDF text vectors with numerical amount features without needing per-tree normalisation." },
                    { title:"Robust to class imbalance", body:'Shopping is 48% of data, groceries just 3%. class_weight="balanced" makes every category equally important.' },
                    { title:"No extensive tuning",       body:"Tree ensembles work well out of the box on tabular + text data. Neural networks need more data for marginal gain." },
                    { title:"Explainable predictions",   body:"Feature importance shows which merchant words drive each prediction — inspectable and debuggable." },
                  ].map(({ title, body }) => (
                    <div key={title} style={{ background:C.surface, borderRadius:8,
                      padding:"12px 14px", marginBottom:8 }}>
                      <div style={{ fontSize:13, fontWeight:600, color:C.ink900,
                        marginBottom:4, display:"flex", alignItems:"center", gap:6 }}>
                        <i className="ti ti-check" style={{ fontSize:13, color:C.green600 }} aria-hidden="true" />
                        {title}
                      </div>
                      <div style={{ fontSize:12, color:C.ink500, lineHeight:1.6 }}>{body}</div>
                    </div>
                  ))}
                  <Divider />
                  <div style={{ fontSize:13, fontWeight:600, color:C.ink500,
                    textTransform:"uppercase", letterSpacing:.7, marginBottom:10 }}>
                    Alternatives considered
                  </div>
                  {[
                    { name:"Logistic Regression",  badge:<Badge text="Tried"                type="warn" /> },
                    { name:"SVM",                  badge:<Badge text="Too slow on 500 feats" type="warn" /> },
                    { name:"BERT fine-tune",        badge:<Badge text="Needs 10K+ rows"      type="warn" /> },
                    { name:"Random Forest",         badge:<Badge text="Chosen"               type="ok"   /> },
                  ].map(({ name, badge }) => (
                    <div key={name} style={{ display:"flex", justifyContent:"space-between",
                      alignItems:"center", padding:"8px 0",
                      borderBottom:`0.5px solid ${C.border}`, fontSize:13 }}>
                      <span style={{ color:C.ink700 }}>{name}</span>
                      {badge}
                    </div>
                  ))}
                </div>
              )}

              {!loading && tab === "limits" && (
                <div>
                  {[
                    { color:C.red600,    title:"Government data, not consumer",
                      body:"Training set is US government procurement — merchants like Grainger dominate. Real consumer spend (Woolworths, Uber) will see lower accuracy." },
                    { color:C.amber600,  title:"65% accuracy ceiling",
                      body:"The dataset categories were not designed for consumer finance. Merchant names alone carry limited signal for procurement spend." },
                    { color:C.amber600,  title:'No "other" category',
                      body:"Dropped from training — it was a catch-all with no learnable signal. Unknown merchants default to keyword rules." },
                    { color:C.ink300,    title:"Static model",
                      body:"No continuous retraining. Adding labelled consumer data and rerunning 03_train.py would materially improve accuracy." },
                  ].map(({ color, title, body }) => (
                    <div key={title} style={{ display:"flex", gap:12, marginBottom:14 }}>
                      <div style={{ width:8, height:8, borderRadius:"50%",
                        background:color, flexShrink:0, marginTop:5 }} />
                      <div>
                        <div style={{ fontSize:13, fontWeight:600, color:C.ink900,
                          marginBottom:3 }}>{title}</div>
                        <div style={{ fontSize:12, color:C.ink500, lineHeight:1.6 }}>{body}</div>
                      </div>
                    </div>
                  ))}
                  <Divider />
                  <div style={{ fontSize:13, fontWeight:600, color:C.ink500,
                    textTransform:"uppercase", letterSpacing:.7, marginBottom:10 }}>
                    How to improve
                  </div>
                  <InfoRow label="Add consumer transaction data" value="→ 85%+ accuracy" />
                  <InfoRow label="BERT merchant embeddings"      value="→ handles new brands" />
                  <InfoRow label="Retrain quarterly"             value="→ stays current" />
                  <InfoRow label="User feedback loop"            value="→ personalised model" />
                </div>
              )}
            </div>
          </div>
        </div>
      , document.body)}
    </>
  )
}